//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jacquard.SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSecrets
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public string Type { get; set; }
        public System.DateTime Created { get; set; }
        public int ClientId { get; set; }
    }
}
