//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jacquard.SSO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceCodes
    {
        public string UserCode { get; set; }
        public string DeviceCode { get; set; }
        public string SubjectId { get; set; }
        public string ClientId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime Expiration { get; set; }
        public string Data { get; set; }
    }
}
