//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jacquard.SSO.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;


    public class ClientRedirectUris
    {
        
        public ClientRedirectUris()
        {
          
        }
    
        [Key]
        public int Id { get; set; }
        public string RedirectUri { get; set; }       
        public int ClientId { get; set; }

    }
}
